# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 343b9509b804a92fb6eb343b6af5924943a734dc1ae3254b6cd540555c04d15b18a198a9b0168f81e3eea6affa404f6062f03050792b08255fbb0e8ee4f1ce01

test:
  secret_key_base: 890c196acea53f044db97fa6150900dbc1bf260b163cc50cad2f47d48681acc8e61401a11ac5574c7a04c35c9c7a17032ac396001d991d5eff86f7906be47ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
